name: Deploy Automatico VPS
on:
  push:
    branches:
      - dev
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Ambiente de Desenvolvimento
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/portal/dev
            git fetch origin dev
            git reset --hard origin/dev
      - name: Deploy Ambiente Oficial (Producao)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /root/portal/prod
            git fetch origin main
            git reset --hard origin/main